"""added BookGenre model

Revision ID: 38de18b47d3b
Revises: 06ef21aeb8a0
Create Date: 2022-11-12 19:24:58.906674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38de18b47d3b'
down_revision = '06ef21aeb8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    # ### end Alembic commands ###
